# Generated by Django 2.1.7 on 2020-05-07 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='releae_year',
            new_name='release_year',
        ),
    ]
